site_name: Zhe's Engineering Notes
nav:
  - Home: index.md
  - Projects:
    - "Booster RF waveform generator": projects/booster-wfg.md
  - About: about.md
theme:
  name: material
  palette:
    scheme: default
  features:
    - search.suggest
    - search.highlight
    - header.autohide
#    - navigation.tabs
extra_css:
  - stylesheets/extra.css
plugins:
  - search
repo_url: https://github.com/SPEAR3-CTRL/engr-notes
repo_name: SPEAR3-CTRL/engr-notes
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
